CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_users_id PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    available BOOLEAN NOT NULL,
    CONSTRAINT pk_item_id PRIMARY KEY (id),
    CONSTRAINT fk_item_owner FOREIGN KEY (owner_id)
    REFERENCES users (id)
    ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    item_id BIGINT NOT NULL,
    booker_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    CONSTRAINT pk_bookings_id PRIMARY KEY (id),
    CONSTRAINT fk_bookings_user FOREIGN KEY (booker_id)
    REFERENCES users (id)
    ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text VARCHAR(1000) NOT NULL,
    item_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    created TIMESTAMP NOT NULL,
    CONSTRAINT pk_comments_id PRIMARY KEY (id),
    CONSTRAINT fk_comments_item FOREIGN KEY (item_id)
    REFERENCES item (id)
    ON DELETE CASCADE,
    CONSTRAINT fk_comments_author FOREIGN KEY (author_id)
    REFERENCES users (id)
    ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS item_requests
(
    id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    description  VARCHAR(100),
    created date,
    CONSTRAINT pk_item_requests PRIMARY KEY (id)
);